use jfe;

CREATE TABLE Usuario (
U_ID INT NOT NULL AUTO_INCREMENT,
U_Nombre VARCHAR(20) NOT NULL,
U_ApellidoP VARCHAR(20) NOT NULL,
U_ApellidoM VARCHAR(20) NOT NULL,
U_Correo VARCHAR(30) NOT NULL UNIQUE,
U_Contraseña VARCHAR(20) NOT NULL,
U_Usuario VARCHAR(20) NOT NULL UNIQUE,
U_Dirección VARCHAR(50),
U_Teléfono BIGINT,
U_Recordar BOOLEAN,
U_Foto BLOB,
CONSTRAINT user_pk PRIMARY KEY (U_ID)
);

CREATE TABLE Categoría (
C_ID INT NOT NULL AUTO_INCREMENT,
C_Categoría VARCHAR(20) NOT NULL UNIQUE,
CONSTRAINT category_pk PRIMARY KEY (C_ID)
);

CREATE TABLE Producto (
P_ID INT NOT NULL AUTO_INCREMENT,
P_Nombre VARCHAR(30) NOT NULL,
P_Descripción TEXT NOT NULL,
P_Unidades INT NOT NULL DEFAULT 1,
P_Precio INT NOT NULL DEFAULT 0,
P_Estrellas INT NOT NULL DEFAULT 0,
P_CategoríaID INT NOT NULL,
CONSTRAINT product_fk FOREIGN KEY (P_CategoríaID)
      REFERENCES Categoría(C_ID),
CONSTRAINT product_pk PRIMARY KEY (P_ID)
);

CREATE TABLE Carrito (
C_UsuarioID INT NOT NULL,
C_ProductoID INT NOT NULL,
CONSTRAINT cart_fk1 FOREIGN KEY (C_UsuarioID)
REFERENCES Usuario(U_ID),
CONSTRAINT cart_fk2 FOREIGN KEY (C_ProductoID)
REFERENCES Producto(P_ID),
CONSTRAINT cart_pk PRIMARY KEY (C_UsuarioID, C_ProductoID)
);

CREATE TABLE Comentario (
C_UsuarioID INT NOT NULL,
C_ProductoID INT NOT NULL,
C_Comentario TEXT NOT NULL,
C_Fecha DATE NOT NULL,
CONSTRAINT coment_fk1 FOREIGN KEY (C_UsuarioID)
REFERENCES Usuario(U_ID),
CONSTRAINT coment_fk2 FOREIGN KEY (C_ProductoID)
REFERENCES Producto(P_ID),
CONSTRAINT coment_pk PRIMARY KEY (C_UsuarioID, C_ProductoID)
);

CREATE TABLE Historial (
H_UsuarioID INT NOT NULL,
H_ProductoID INT NOT NULL,
H_Unidades INT NOT NULL,
H_Total DECIMAL(7,2) NOT NULL,
CONSTRAINT record_fk1 FOREIGN KEY (H_UsuarioID)
REFERENCES Usuario(U_ID),
CONSTRAINT record_fk2 FOREIGN KEY (H_ProductoID)
REFERENCES Producto(P_ID),
CONSTRAINT record_pk PRIMARY KEY (H_UsuarioID, H_ProductoID)
);

CREATE TABLE Imagen (
I_ID INT NOT NULL AUTO_INCREMENT,
I_Imagen BLOB NOT NULL,
I_ProductoID INT NOT NULL,
CONSTRAINT image_fk FOREIGN KEY (I_ProductoID)
REFERENCES Producto(P_ID),
CONSTRAINT image_pk PRIMARY KEY (I_ID)
);

CREATE TABLE Video (
V_ID INT NOT NULL AUTO_INCREMENT,
V_Video BLOB NOT NULL,
V_ProductoID INT NOT NULL,
CONSTRAINT video_fk FOREIGN KEY (V_ProductoID)
REFERENCES Producto(P_ID),
CONSTRAINT video_pk PRIMARY KEY (V_ID)
);
